# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY server.py /app/server.py
COPY models.py /app/models.py
COPY historial /app/historia
COPY microservices.json /app/microservices.json
COPY requirements.txt /app/requirements.txt
COPY .env /app/.env


# Instala las dependencias de Python y el cliente Docker
RUN pip install --no-cache-dir -r requirements.txt \
    && apt-get update \
    && apt-get install -y docker.io \
    && apt-get clean

# Expone el puerto en el que correrá el servidor
EXPOSE 5000

# Comando para ejecutar el servidor
CMD ["python", "server.py"]