# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY server.py /app/server.py
COPY models.py /app/models.py
COPY requirements.txt /app/requirements.txt

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto en el que correrá el servidor
EXPOSE 5000

# Comando para ejecutar el servidor
CMD ["python", "server.py"]